### ISSUE TITLE
MCP2515 clock speed setting default at 16mhz. 

### ISSUE THREAD

**Issue by coultl6556** [designer2k2/EMUcan#13]
Just a suggestion but seems like nearly all of the MCP2515 boards have a 8mhz clock and the code defaults to 16mhz. Took me a while to figure it out. Maybe update this line of code with: 

mcp2515.setBitrate(CAN_500KBPS, MCP_8MHZ);

That set's the proper clock speed and also surfaces the fact that if can be changed. Appreciate this and getting it working in my car now!

**Comment by designer2k2** [comment]
Hello,

thanks for pointing this out! I added the 8MHz into the examples together with a note that it has to be checked.
