### ISSUE TITLE
Increase update speed?

### ISSUE THREAD

**Issue by coultl6556** [designer2k2/EMUcan#14]
Got things working with my ECUMaster Black. So cool. Running an Arduino Nano Every and a MCP2515 breakout board. I'd like to use the MAP data to run a boost gauge (stepper motor and run by the Arduino) but the update speed seems too slow for this to work. It seems like it updates at something like 1hz. Is there a limitation that I'm hitting or should it be faster? I think I'd need it to pull values at about 50hz minimum to get a gauge to work decent.  Any tip on how to get a faster update on the EMU values over CAN? Thank you!

Video of my custom boost gauge here: https://youtu.be/ZjTRC6D3Vsw

**Comment by designer2k2** [comment]
Hello,
that´s a nice integration 👍 

The Black is sending the MAP with 20Hz, see this File on a PC with the Software for the Black installed:
file:///C:/Program%20Files%20(x86)/Ecumaster/EMU%20Black/Help/EN/emuCANStream.html

This 20Hz are enough to give a smooth view on moving display´s.

EMUcan is capable to receive this 20Hz easily, but getting the full speed on a Nano Every needs some care taken in the software.
Even on a strong Teensy 4 (600MHz clock speed) this needs some considerations.

A good example is the Arduino Blink without Delay: https://docs.arduino.cc/built-in-examples/digital/BlinkWithoutDelay

This practise of running a loop at maximum speed to capture every CAN frame and then taking actions on given intervalls works well on Arduinos.  The same way i build the examples provided with EMUcan.

In the video was also a small display, how fast is this update? Some displays take quite a while to send the data to. 
And how is the stepper driven?  Is the code blocked while the needle is moving?

**Comment by designer2k2** [comment]
Yes lets keep this open here.

(i modified your comment to have the code formatted)

The programm looks ok, one thing is that you update the display on very loop.  That will slow down the loop a lot, try to get the loop running much faster and update the display at a given intervall.

Place the display update in the "Serial out every second" but let it update like every 250ms.

**Comment by coultl6556** [comment]
Well, that totally worked...perfectly. Gauge works great, super responsive. Screen is updating even faster now. Something about updating the screen on every loop was slowing everything way down. 

One note for others if they build something similar. I used the TPS value to test the gauge that way I can get instant feedback when I push the pedal with the car off. 

Updated code here in case it's helpful to anyone:

`// EMUCan Lib Simple Test Example

// Example to be run on Arduino (Nano) with MCP2515
// Configure the EMU Black to send the CAN Stream at 500KBPS

// This MCP2515 Lib is used:
// https://github.com/autowp/arduino-mcp2515


// https://www.designer2k2.at
// Stephan Martin 27.12.2022


#include "EMUcan.h"
// EMU initialized with base ID 600:
EMUcan emucan(0x600);

int iat = 0;

//screen code
#include <SPI.h>
#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>
#define SCREEN_WIDTH 128 // OLED display width, in pixels
#define SCREEN_HEIGHT 32 // OLED display height, in pixels
// Declaration for an SSD1306 display connected to I2C (SDA, SCL pins)
// The pins for I2C are defined by the Wire-library. 
// On an arduino UNO:       A4(SDA), A5(SCL)
// On an arduino MEGA 2560: 20(SDA), 21(SCL)
// On an arduino LEONARDO:   2(SDA),  3(SCL), ...
#define OLED_RESET     -1 // Reset pin # (or -1 if sharing Arduino reset pin)
#define SCREEN_ADDRESS 0x3C ///< See datasheet for Address; 0x3D for 128x64, 0x3C for 128x32
Adafruit_SSD1306 display(SCREEN_WIDTH, SCREEN_HEIGHT, &Wire, OLED_RESET);

// needle code
#include "SwitecX25.h"

#include <mcp2515.h>
struct can_frame canMsg;
// MCP2515 with chip select (CS) pin 10:
MCP2515 mcp2515(10);

// Code for stepper needle
// 315 degrees of range = 315x3 steps = 945 steps - changed to 630 steps
// declare motor1 with 945 steps on pins 4-7
SwitecX25 motor1(630,3,4,7,8);
// Boost in kPa
int boost = 0;
int needlepos = 0;

unsigned long previousMillis = 0;
const long interval = 250;

static const unsigned char PROGMEM quattro_glcd_bmp[] =
{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xE0, 0x03, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xE0, 0x03, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0xFF, 0x8F, 0xFE, 0x00, 0x00, 0x00, 0x00, 0x00,
0x3F, 0xFF, 0xC7, 0x00, 0x07, 0x1F, 0xFF, 0xF3, 0xFF, 0xCF, 0xFE, 0x07, 0xFF, 0xC3, 0xFF, 0xFC,
0x7F, 0xFF, 0xE7, 0x00, 0x07, 0x3F, 0xFF, 0xF8, 0xF0, 0x03, 0x80, 0x0F, 0xFF, 0xE7, 0xFF, 0xFE,
0xFF, 0xFF, 0xE7, 0x00, 0x07, 0x3F, 0xFF, 0xFC, 0xE0, 0x03, 0x80, 0x0F, 0xFF, 0xE7, 0xFF, 0xFF,
0xF0, 0x00, 0xE7, 0x00, 0x07, 0x38, 0x00, 0x3C, 0xF0, 0x33, 0x81, 0xCE, 0x00, 0xE7, 0x00, 0x0F,
0xF0, 0x00, 0xF7, 0x00, 0x07, 0x38, 0x00, 0x3C, 0xF0, 0x7B, 0x81, 0xCE, 0x00, 0x67, 0x00, 0x0F,
0xF0, 0x00, 0xF7, 0x80, 0x0F, 0x3C, 0x00, 0x3C, 0xF0, 0x73, 0xC1, 0xCE, 0x00, 0x07, 0x80, 0x0F,
0x7F, 0xFE, 0xF7, 0xFF, 0xFF, 0x3F, 0xFF, 0xBC, 0xFF, 0xF3, 0xFF, 0xCE, 0x00, 0x07, 0xFF, 0xFE,
0x3F, 0xFE, 0xF3, 0xFF, 0xFE, 0x1F, 0xFF, 0xBC, 0x7F, 0xE1, 0xFF, 0x8E, 0x00, 0x03, 0xFF, 0xFC,
0x00, 0x00, 0xF0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0xF0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0xF0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0xE0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};

void setup() {



//diplay code
display.setRotation(0);

  // put your setup code here, to run once:
  Serial.begin(115200);

    // SSD1306_SWITCHCAPVCC = generate display voltage from 3.3V internally
  if(!display.begin(SSD1306_SWITCHCAPVCC, SCREEN_ADDRESS)) {
    Serial.println(F("SSD1306 allocation failed"));
    for(;;); // Don't proceed, loop forever
  }

  Serial.print("EMUCAN_LIB_VERSION: ");
  Serial.println(EMUCAN_LIB_VERSION);

  Serial.println("------- CAN Read ----------");

  mcp2515.reset();
  mcp2515.setBitrate(CAN_500KBPS, MCP_8MHZ);
  mcp2515.setNormalMode();

//display code
  display.clearDisplay();
  display.drawBitmap(0, 0, quattro_glcd_bmp, 128, 32, 1);
  display.display();
  delay(7000);
  display.clearDisplay();

// needle code - run motor against stop to re-zero
 motor1.zero();   // this is a slow, blocking operation
 //motor1.setPosition(0);
delay(1000);
 //display.clearDisplay();

}




void loop() {

// Call the EMUcan lib with every received frame:
  if (mcp2515.readMessage(&canMsg) == MCP2515::ERROR_OK) {
    emucan.checkEMUcan(canMsg.can_id, canMsg.can_dlc, canMsg.data);
  }

 //needle code
 if (emucan.emu_data.MAP < 88) {
  boost = 88;
}
  else {
  boost = emucan.emu_data.MAP;
}
  //needlepos = (emucan.emu_data.TPS*5.4);
  needlepos = (((boost-88))*2.7);
  motor1.setPosition(needlepos);
  //updateBlocking();
  motor1.update();



if (emucan.emu_data.IAT > 99) {
  iat = 99;
}
  else {
    iat = emucan.emu_data.IAT;
}

int oilpress = round(emucan.emu_data.oilPressure*10);
  motor1.update();
int ethcontent = round(emucan.emu_data.flexFuelEthanolContent);
  motor1.update();


  // Serial out every second:
unsigned long currentMillis = millis();
  if (currentMillis - previousMillis >= interval) {
    previousMillis = currentMillis;

  if (emucan.EMUcan_Status() == EMUcan_RECEIVED_WITHIN_LAST_SECOND){
  display.clearDisplay();
  display.setTextSize(3);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(1, 6);
  display.println(oilpress);
// display.println(emucan.emu_data.TPS);
  display.setCursor(45, 6);
  display.println(iat);
  display.setCursor(90, 6);
  display.println(ethcontent); 
  display.display();    
}

else{
  //display.clearDisplay();
 display.setTextSize(3); // Draw 2X-scale text
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(1, 6);
  display.println("CAN ERR");
  display.display();  
}
  }
    //if (emucan.EMUcan_Status() == EMUcan_RECEIVED_WITHIN_LAST_SECOND) {
      //Serial.print(emucan.emu_data.RPM);
      //Serial.print(";");
      //Serial.print(emucan.emu_data.TPS);
      //Serial.print(";");
      //Serial.print(emucan.emu_data.IAT);
      //Serial.print(";");
      //Serial.print(emucan.emu_data.MAP);
      //Serial.print(";");
      //Serial.println(emucan.emu_data.pulseWidth);
   // } else {
   //   Serial.println("No communication from EMU");
    // }
   // if (emucan.emu_data.flags1 & emucan.F_IDLE) {
     // Serial.println("Engine Idle active");
   // }
   // if (emucan.decodeCel()) {
   //   Serial.println("WARNING Engine CEL active");
  //  }
 // }
  
  //display.clearDisplay();

}
`

**Comment by designer2k2** [comment]
That looks great in the video! 💯 

One further tweak could be to take **setTextColor** and  **setTextSize** out of the loop. If its never changed it can go in setup. And therefore speed up the loop further. 
Just would need to be tested as im not shure if the Adafruit_SSD1306 will remember this or the setting is needed every time.

Small note on the code, are you using the Arduino IDE? For readability try:
Selecting Edit > Auto Format or pressing CTRL + T on Windows/Linux or CMD + T on MacOS when writing a sketch in the Arduino IDE 2 will automatically format the sketch
This will format, or better call it indent the code to make it "nicer" to read.

**Comment by coultl6556** [comment]
Will do. Thank you!
