### ISSUE TITLE
Cooling Fan Flag?

### ISSUE THREAD

**Issue by coultl6556** [designer2k2/EMUcan#16]
I’d like to read when the cooling fan is on but I don’t see a field or flag for that in the full list. Seems like everything is covered so I must be missing it. Appreciate any help!

**Comment by designer2k2** [comment]
Hello,
the Cooling Fan is inside the OUTFLAGS4,  but i made a typo and called the field F_CS and not F_CF.  
I just pushed a fix for the naming...

So to check if the coolant fan is running looks like:
```++
if (emucan.emu_data.outflags4 & emucan.F_CF) {
    Serial.println("Coolant fan active");
}
```

**Comment by coultl6556** [comment]
Awesome. I was wondering what CS was. Ha. Thank you!
